### ISSUE TITLE
v2.0.0 fails with HTTP status 400

### ISSUE THREAD

**Issue by pentago** [DependencyTrack/gh-upload-sbom#16]
@nscuro compared to v1.0.0 which works fine, v2.0.0 fails with HTTP status 400, no logs why though.
Any ideas?

**Comment by nscuro** [comment]
Should be fixed in [v2.0.1](https://github.com/DependencyTrack/gh-upload-sbom/releases/tag/v2.0.1), please give that a try.

**Comment by pentago** [comment]
v2.0.1 works fine.
