### ISSUE TITLE
Update Documentation (input keys)

### ISSUE THREAD

**Issue by a-schyja** [DependencyTrack/gh-upload-sbom#27]
Please update the documentation and examples, as they use capitilized inputs (apiKey) while all keys expected to be lowercase (apikey).

**Comment by nscuro** [comment]
Inputs are treated case-insensitively by GitHub Actions. Behind the scenes, inputs are just environment variables: https://github.com/actions/toolkit/blob/6c4e082c181a51609197e536ef5255a0c9baeef7/packages/core/src/core.ts#L126-L138
