### ISSUE TITLE
Response status code: Finished uploading BOM to Dependency-Track server. Error: Problem with request: read ECONNRESET Error: read ECONNRESET

### ISSUE THREAD

**Issue by shahidakhter786** [DependencyTrack/gh-upload-sbom#28]
I am facing this issue and dont know how to resolve it, i have tried almost everything but after 4 min 45 seconds, it just gives me this error:
Response status code:
Finished uploading BOM to Dependency-Track server.
Error: Problem with request: read ECONNRESET
Error: read ECONNRESET

if anyone can help me with this?

**Comment by SeifElsherif** [comment]
I do have the same problem, I use the follwoing workaround so it doesn't consume lot of time

`timeout-minutes: 1
  continue-on-error: true`

**Comment by nscuro** [comment]
Fixed in https://github.com/DependencyTrack/gh-upload-sbom/pull/35
