### ISSUE TITLE
Bom upload fails if parent UUID is specified

### ISSUE THREAD

**Issue by gilesrapkinb** [DependencyTrack/gh-upload-sbom#30]
If you try and upload with a parent UUID set in the `parent` field you get 400 API response.

From the docs it looks like field name should be `parentUUID` instead of `parent`. https://docs.dependencytrack.org/usage/cicd/

**Comment by nscuro** [comment]
Fixed in https://github.com/DependencyTrack/gh-upload-sbom/pull/35
