### ISSUE TITLE
Get 415 error when bom file is too large

### ISSUE THREAD

**Issue by leichen-eizo** [DependencyTrack/gh-upload-sbom#31]
When upload bom get a  415 error.

It may due to the limit of put
```
The maximum allowed length of the bom value is 20'000'000 characters. When uploading large BOMs, the POST endpoint is preferred, as it does not have this limit.

Requires permission BOM_UPLOAD
```

Can you change the PUT into POST?

https://github.com/DependencyTrack/gh-upload-sbom/blob/1f0526714a54aeb1cdf780889cf1e917c477d775/index.js#L77

**Comment by nscuro** [comment]
Duplicate of #7
